### ISSUE TITLE
sale_object.rent_or_sale

### ISSUE THREAD

**Issue by notcrack** [woblers/rightmove_webscraper.py#9]
Hi, 

I've been trying to get the code up and running, but I can't work out how to resolve this error 

sale_object.rent_or_sale
AttributeError: 'rightmove_data' object has no attribute 'rent_or_sale'

I'm probably being stupid, but if you have any advice on it I'd appreciate it. 

Cheers

**Comment by woblers** [comment]
Hi @notcrack thanks for flagging this up. I recently updated the whole package and changed the API and the .rent_or_sale attribute is no longer exposed (since it's not really necessary for the object to tell you what you searched for).

I got a bit behind with updating the README but have now done this so if you follow the new instructions through it should all work.

Toby
